# Each route describes how an incoming URL will be processed by Platform.sh.

routes:
    "https://{default}/":
        type: upstream
        upstream: "ll_project:unix"

    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"